### ISSUE TITLE
Cant kill.

### ISSUE THREAD

**Issue by KinyWolf** [Town-of-Impostors/TownOfImpostors#49]
Ok so I just downloaded the last version 2.0.3 and I became an impostor but my kill button didn't work. I mean I can't click it.

**Comment by JonyKasual** [comment]
Do you happen to be playing in a public lobby where other players do not have the mod installed?

**Comment by JonyKasual** [comment]
Closing issue. No response and this 'bug' is often tied to others in the lobby not having the mod installed.
