### ISSUE TITLE
Meetings don't end correctly with snipers

### ISSUE THREAD

**Issue by Cargonat** [Town-of-Impostors/TownOfImpostors#53]
# How to reproduce
1. Be in a meeting with a sniper.
2. Have everyone except one person vote.
3. Have the remaining person die via Sniper (either because they get shot or because they are the Sniper choosing wrong).

## Expected result
The meeting ends because everyone who is left alive has voted.

## Actual result
The meeting continues until the timer runs out.

**Comment by AJMix** [comment]
Fixed in 2.0.6, closing ticket
