### ISSUE TITLE
Free chat

### ISSUE THREAD

**Issue by DaLUCKY** [Town-of-Impostors/TownOfImpostors#55]
Even when I enable free chat, it doesn't let me. I say this mod should have free chat and among us in it itself so we just have to extract it to an empty folder!

**Comment by JonyKasual** [comment]
Have you signed in to your Among Us account? That is a requirement to be able to free chat. We will not bypass the authentications set by Innersloth.

Also, bundling the game would be illegal digital distribution, of which we do not condone and we ask that you do not ask any further for it.

**Comment by JonyKasual** [comment]
Closing Ticket.
