### ISSUE TITLE
[Error](https://i.imgur.com/CFChfMU.png) Error signing in.

### ISSUE THREAD

**Issue by JacobHin2** [Town-of-Impostors/TownOfImpostors#57]
Installed for Epic Games and received this [error](https://i.imgur.com/CFChfMU.png)

**Comment by JonyKasual** [comment]
Launch Among Us through the Epic Launcher first and Sign in to your Among Us account. If it has not yet been done so, it will also open a browser to direct you to allow Innersloth to link to the Epic Games account.
